### DISCUSSION TITLE
Managed prometheus is blocked by the istio

### DISCUSSION THREAD

**Discussion by PawelHaracz** [GoogleCloudPlatform/prometheus-engine#340] [Q&A] [answered]
Hey,
I enabled manages prometheus on my GKE cluster but I don’t gather any metrics from my pods. It’s worth to mention that my cluster uses istio service mesh, and it’s injected into every pod. Additionally, when I use Prometheus operator the metrics are scraped. Can someone of you have had a similar issue and know how to resolve it?

**Comment by lyanco** [comment]
Managed Prometheus doesn't scrape anything until you install a PodMonitor, which configures scraping. See https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed for details, and https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters for some examples.

**Reply by PawelHaracz** [reply]
I forgot to mention earlier I already configured podMonitor and even service monitor, Attached some example configurations that I use:

```YAML
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name:  {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
  - port: 80
    interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
  - targetPort: 80
    interval: 30s
    path:  "/metrics"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        sidecar.istio.io/proxyCPULimit: "2.0"
        sidecar.istio.io/proxyMemoryLimit: "1Gi"
        sidecar.istio.io/proxyCPU: "0.10"
        sidecar.istio.io/proxyMemory: "128Mi"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
        prometheus.io/scheme: http
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.containerRegistry }}/{{ .Chart.Name }}:{{ .Chart.Version }}"
          resources:
            limits:
              memory: {{ .Values.memory.limit }}
              cpu: {{ .Values.cpu.limit }}
            requests:
              memory: {{ .Values.memory.request }}
              cpu: {{ .Values.cpu.request }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-CM
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2

```
