### DISCUSSION TITLE
Monitoring Flux

### DISCUSSION THREAD

**Discussion by heretic098** [GoogleCloudPlatform/prometheus-engine#405] [Q&A] [answered]
Hi, I hope it's ok to post here, I'm trying to monitor Flux using Google managed prometheus in GKE. [The flux docs](https://fluxcd.io/flux/guides/monitoring/) have a set of instructions for deploying another prometheus stack which *I think* ultimately comes down to deploying a custom [PodMonitor resource](https://github.com/fluxcd/flux2/blob/main/manifests/monitoring/monitoring-config/podmonitor.yaml). I naively tried changing the apiVersion and kind on the manifest and trying to install it but of course that didn't work :(

Can anyone suggest what the manifest ought to look like based on this hacked version:

    apiVersion: monitoring.googleapis.com/v1
    kind: PodMonitoring
    metadata:
      name: flux-system
      namespace: flux-system
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
    spec:
      namespaceSelector:
        matchNames:
          - flux-system
      selector:
        matchExpressions:
          - key: app
            operator: In
            values:
              - helm-controller
              - source-controller
              - kustomize-controller
              - notification-controller
              - image-automation-controller
              - image-reflector-controller
      podMetricsEndpoints:
        - port: http-prom
          relabelings:
            # https://github.com/prometheus-operator/prometheus-operator/issues/4816
            - sourceLabels: [__meta_kubernetes_pod_phase]
              action: keep
              regex: Running

Sorry for the n00b question, I've not worked with prometheus before.

**Comment by pintohutch** [comment, marked as answer]
Hi @heretic098,

Apologies for the delayed response. So [`PodMonitoring`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/doc/api.md#podmonitoring) as a different API spec from the prometheus-operator [`PodMonitor`](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.PodMonitor), which is why you're facing this issue (e.g. there's no `namespaceSelector` in `PodMonitoring`).

However, you should be able to modify your resource to look something like:
```yaml
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - helm-controller
      - source-controller
      - kustomize-controller
      - notification-controller
      - image-automation-controller
      - image-reflector-controller
  endpoints:
  - port: http-prom
    interval: 30s
```

I've never used Flux, so I may not have the `PodMonitoring` totally correct for scraping it, but we've had other folks post about their usage of it, e.g. https://github.com/GoogleCloudPlatform/prometheus-engine/issues/364. Maybe they have a `PodMonitoring` they can suggest.
