### ISSUE TITLE
Missing metrics from PodMonitoring resource

### ISSUE THREAD

**Issue by elebioda** [GoogleCloudPlatform/prometheus-engine#152]
I setup kube-state-metrics and a PodMonitoring resource on the deployment

```
apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
  - port: http
    interval: 30s # Leave at 30 so we dont get charged 1 Billion dollaridoos 
```

But there are numerous metrics that are not being scraped and pushed to GMP

I made sure kube-state-metrics is publishing them.. for example our GMP is showing no metrics for a specific metric

```
PromQL Query: kube_deployment_status_replicas_available{deployment="tracking-order-api-order-tracking-api"}
Query duration: 0.6 sec
Series returned: 0
```

But when I check the metrics on kube-state-metrics they are showing as present on the /metrics endpoint

```
kube_deployment_status_replicas_available{namespace="prod",deployment="tracking-order-api-order-tracking-api"} 5
```

**Comment by lyanco** [comment]
kube-state-metrics monitors cluster state and is better handled by a ClusterPodMonitoring resource instead. Could you try the following and see if it works:

```
apiVersion: monitoring.googleapis.com/v1alpha1
kind: ClusterPodMonitoring
metadata:
  name: kube-state-metrics
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
  - port: http
    interval: 30s
  targetLabels:
    metadata: []
```

We'll soon have best-practice copy-and-paste CRs for kube state and other common exporters (e.g. node-exporter).

**Comment by elebioda** [comment]
> kube-state-metrics monitors cluster state and is better handled by a ClusterPodMonitoring resource instead. Could you try the following and see if it works as expected:
> 
> ```
> apiVersion: monitoring.googleapis.com/v1alpha1
> kind: ClusterPodMonitoring
> metadata:
>   name: kube-state-metrics
> spec:
>   selector:
>     matchLabels:
>       app: kube-state-metrics
>   endpoints:
>   - port: http
>     interval: 30s
>   targetLabels:
>     metadata: []
> ```
> 
> We'll soon have best-practice copy-and-paste CRs for kube state and other common exporters (e.g. node-exporter).

Im not sure I understand the benefits of the ClusterPodMonitoring vs the PodMonitoring. kube-state-metrics typically runs as a single replica as it would result in duplication of metrics. Could you elaborate on why ClusterPodMonitoring is better?

**Comment by elebioda** [comment]
> What I think is happening in your original situation is that the namespace in which kube-state is running (and which the PodMonitoring is installed in) is overriding the namespace label set on each individual kube-state metric. So queries that include the namespace "prod" are returning a null set.
> 
> I believe PodMonitorings hard-enforce the namespace in which they are installed, so they won't work at all for kube-state. ClusterPodMonitorings also try to add namespace, but by adding `targetLabels: metadata:[]`, you tell the system to not infer/overwrite the namespace label. So the namespace on each kube-state metric will be respected and your queries will work as expected.

Hmm ok I think I sort of get what you mean. I should have added this info, as I show in the example query, I am trying to query a specific deployment, this One deployment's metrics are missing for about 30 minutes rite now. Other deployment metrics are present on time of query 30 seconds, but not the one I showed above. Not sure if this changes your theory.

**Comment by lyanco** [comment]
I'd try using the ClusterPodMonitoring I added above and see if that fixes it. If it doesn't, then we can investigate further.

**Comment by elebioda** [comment]
The manifest you provided is not supported by the controller. Looks like there is a discrepancy between what the managed prometheus CRD it installs. I checked the CRD in our cluster and it does not contain the metadata field. 

```
              targetLabels:
                description: Labels to add to the Prometheus target for discovered
                  endpoints
                properties:
                  fromPod:
                    description: 'Labels to transfer from the Kubernetes Pod to Prometheus
                      target labels. In the case of a label mapping conflict: - Mappings
                      at the end of the array take precedence.'
                    items:
                      description: LabelMapping specifies how to transfer a label
                        from a Kubernetes resource onto a Prometheus target.
                      properties:
                        from:
                          description: Kubenetes resource label to remap.
                          type: string
                        to:
                          description: Remapped Prometheus target label. Defaults
                            to the same name as `From`.
                          type: string
                      required:
                      - from
                      type: object
                    type: array
                type: object
```
