### ISSUE TITLE
Support metrics from other GCP projects

### ISSUE THREAD

**Issue by djfinnoy** [GoogleCloudPlatform/prometheus-engine#154]
It appears that metrics from other GCP projects are filtered away by the managed prometheus instance.

We would like to use prometheus and alertmanager to monitor our Cloud Functions. 
Prometheus is running in our GKE cluster in `current-project`, while some (but not not all) of our Cloud Functions belong in a different GCP project (`other-project`).

I've installed the [prometheus stackdriver exporter](https://github.com/prometheus-community/stackdriver_exporter), and got it working with our managed Prometheus instance.

When I curl the `/metrics` endpoint of the exporter, I find lots of results for both projects.
However, in the GCP Console, I can only find the subset of these metrics where `project_id` matches `current-project`.
The metrics where `project_id` matches `other-project` do not make it into Prometheus, even though they are definitely present under the `/metrics` endpoint

I tried adding the following `collections` to the `OperatorConfig`, but it didn't help:
```
apiVersion: monitoring.googleapis.com/v1alpha1
kind: OperatorConfig
metadata:
  name: config
  namespace: gmp-public
collection:
  filter:
    matchOneOf:
      - '{project_id="current-project"}'
      - '{project_id="other-project"}'
```

Concidentally, I see the following error message in the `collector` logs when attempting to get metrics from `other-project`:
```
collector-lp6gq prometheus ts=2022-03-08T13:03:21.525Z caller=log.go:124 component=gcm_exporter level=error msg="send batch" size=4 err="rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.create denied (or the resource may not exist)."
```

The service account used by Prometheus only has `roles/monitoring.metricsWriter` for `current-project`. Is it possible that `project_id` is being used under the hood, and that Prometheus is trying to write the metrics to stackdriver in `other-project` instead?
