### ISSUE TITLE
Allow "--export.XXX" args to be set with environment variables

### ISSUE THREAD

**Issue by superbrothers** [GoogleCloudPlatform/prometheus-engine#171]
When using GMP with Prometheus Operator, setting `--export.XXX` args in Prometheus CR will overwrite args in a StatefulSet created from Prometheus CR. Therefore, it is currently necessary to explicitly add args generated from Prometheus CR spec.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
spec:
  ...
  containers:
    - args:
      - --export.credentials-file=/gmp/key.json
      - --export.label.project-id=xxxxxxxx
      - --export.label.location=xxxxxxxxxxxx
      - --export.match=xxxxxxxxxxxxx
      # The following arguments are generated by the Prometheus Operator, but
      # are explicitly added because they would be overwritten if the above
      # GMP arguments are added.
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=10d
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --web.config.file=/etc/prometheus/web_config/web-config.yaml
      name: prometheus
```

This is a tedious task. This problem can be avoided by allowing them to be set in environment variables. Currently, only `--export.credentials-file` arg can be set with an environment variable.
