### ISSUE TITLE
Add support for targeting services for scraping

### ISSUE THREAD

**Issue by salineselin** [GoogleCloudPlatform/prometheus-engine#192]
An increasing number of providers are placing their metrics endpoints behind a service rather than digesting them directly from a deployment. [Kyverno](https://github.com/kyverno/kyverno/blob/main/charts/kyverno/templates/service.yaml#L24-L47) and [ArgoCD](https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml#L9536-L9551) are notable examples. Other implementations of Prometheus collectors have a CRD that allows you to scrape metrics by targeting a service.
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml

The only way to target these endpoints currently is to ignore the service, parse the deployment that's generating metrics for a label you can use, and construct a `PodMonitoring` resource for each deployment that generates metrics. It sucks because it makes what should be a single simple monitoring resource into multiple monitoring resources that are generally more brittle.

**Comment by salineselin** [comment]
There might be some way to use the `podMonitoring` resource to listen on a service that I'm just not aware of. Here's an example yaml based on the `prom-example` example in GCP's documentation [here](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#config-mgd-collection) that includes a service. I feel like this *should* work, but it doesn't...
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-example
  namespace: gmp-test
  labels:
    app: prom-example
spec:
  selector:
    matchLabels:
      app: prom-example
  replicas: 3
  template:
    metadata:
      labels:
        app: prom-example
    spec:
      containers:
        - image: nilebox/prometheus-example-app@sha256:dab60d038c5d6915af5bcbe5f0279a22b95a8c8be254153e22d7cd81b21b84c5
          name: prom-example
          ports:
            - name: metrics
              containerPort: 1234
          command:
            - "/main"
            - "--process-metrics"
            - "--go-metrics"
---
apiVersion: v1
kind: Service
metadata:
  name: gmp-test-service
  namespace: gmp-test
spec:
  ports:
    - port: 5678
      protocol: TCP
      targetPort: metrics
  selector:
    app: prom-example
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: prom-example
  namespace: gmp-test
spec:
  selector:
    matchLabels:
      app: prom-example
  endpoints:
    - port: 5678
      interval: 5s
```
