### ISSUE TITLE
Honor labels option

### ISSUE THREAD

**Issue by danielkucera** [GoogleCloudPlatform/prometheus-engine#215]
Hello,

I am trying to scrape pushgateway using PodMonitoring object. In general it works but it does relabel `job` and `instance` labels.

To prevent relabeling, [one can specify](https://github.com/prometheus/pushgateway#about-the-job-and-instance-labels) `honor_labels: true` in scrape config but this is currently not possible with PodMonitoring object.

Can you please add an option to enable configuration of `honor_labels`?

**Comment by lyanco** [comment]
Hey Daniel, could you talk a little about your use case for not relabeling the job and instance labels?

e.g. what labels do you want, and what labels are you getting from GMP?

**Comment by danielkucera** [comment]
Hi Lee,

I want to ingest metrics from external servers. For this purpose I have deployed [pushgateway](https://github.com/prometheus/pushgateway) and I am pushing metrics from node_exporter as described [here](https://gist.github.com/elritsch/60cbbdcec4d3f1519ce35dc23242ac1f)

When I use PodMonitoring for that pushgateway, 
```
apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: pushgateway
  namespace: gmp-frontend
spec:
  selector:
    matchLabels:
      app: pushgateway
  endpoints:
  - port: http
    interval: 60s
    path: /metrics
```
everything works correctly but the original `instance` and `job` labels are changed to `external_instance` and `external_job` and the standard dashboard no longer works.

I would prefer having the option to keep the original labels rather than manually modifying all dashboards.
