### ISSUE TITLE
Is there a way to scrape metrics from kube-api-server?

### ISSUE THREAD

**Issue by alpenfritz** [GoogleCloudPlatform/prometheus-engine#271]
We would like to scrape metrics from kube-api-server, like what kube-prometheus-stack is doing using a [servicemonitor](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kube-api-server/servicemonitor.yaml). Is this possible? We understand there is only podmonitor CR in GMP.
```yaml
# Source: kube-prometheus-stack/templates/exporters/kube-api-server/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apiserver
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: https
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
      insecureSkipVerify: false
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
```
