### ISSUE TITLE
self-managed istio installation: istiod scraping

### ISSUE THREAD

**Issue by MaciekLeks** [GoogleCloudPlatform/prometheus-engine#281]
I've been trying to scrape istio control plane:
Using Prometheus-Operator I would prepare something like this:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: istio-system
spec:
  jobLabel: istio
  targetLabels: [app]
  selector:
    matchExpressions:
    - {key: istio, operator: In, values: [pilot]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    interval: 15s
```
Yep, via k8s service. OK, we do not have ServiceMonitor CRD so, I'm trying with your `[Cluster]PodMonitoring` CRD.
```
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:      
  name: istiod
  namespace: istio-system
spec:
  endpoints:
  - interval: 15s    
    port: 15014
  selector:
    matchLabels:
      app: istiod
  # matchExpressions = [{
  #   key      = "istio"
  #   operator = "In"
  #   values   = ["pilot"]
  #   }
  # ]
```
The final Prometheus config:
```
apiVersion: v1
data:
  config.yaml: |
    global: {}
    scrape_configs:
        - job_name: ClusterPodMonitoring/istiod/15014
          honor_timestamps: false
          scrape_interval: 15s
          scrape_timeout: 15s
          metrics_path: /metrics
          follow_redirects: true
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app[]
              regex: istiod
              action: keep
            - source_labels: [__meta_kubernetes_namespace[]
              target_label: namespace
              action: replace
            - source_labels: [__meta_kubernetes_pod_name[]
              target_label: pod
              action: replace
            - source_labels: [__meta_kubernetes_pod_container_name[]
              target_label: container
              action: replace
            - target_label: job
              replacement: istiod
              action: replace
            - source_labels: [__meta_kubernetes_pod_name[]
              target_label: __tmp_instance
              action: replace
            - source_labels: [__meta_kubernetes_pod_controller_kind, __meta_kubernetes_pod_node_name[]
              regex: DaemonSet;(.*)
              target_label: __tmp_instance
              replacement: $1
              action: replace
            - source_labels: [__meta_kubernetes_pod_container_port_number[]         #?
              regex: (15014)? #?
              action: keep #?
            - source_labels: [__tmp_instance[]
              target_label: instance
              replacement: $1:15014
              action: replace
            - source_labels: [__meta_kubernetes_pod_ip[]
              target_label: __address__
              replacement: $1:15014
              action: replace          
          kubernetes_sd_configs:
            - role: pod
              follow_redirects: true
              selectors:
                - role: pod
                  field: spec.nodeName=$(NODE_NAME)
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-30T07:10:14Z"
  name: collector
  namespace: gmp-system
```

Port 15014 is not declared anyway in the `istiod` POD definition, but it's the scraping port:
- annotation of the istiod POD snippet:
```
 prometheus.io/port: "15014"
 prometheus.io/scrape: "true"
```
Curling over that port works good (e.g. `curl http://<istiod_pod>:15014/metrics`).

So my metrics are empty for my `istiod` job. Looking at the relabel_config I came out to the conslusion that is because of `#?` part. Isn't it?
If yes, please tell me how to scrape on non-declarative Prometheus ports. If not, so why it is not working?
