### ISSUE TITLE
Example for alert manager config

### ISSUE THREAD

**Issue by naveensrinivasan** [GoogleCloudPlatform/prometheus-engine#290]
Is there an example for alert manager config.

``` yaml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Alertmanager's default port is 9093
        - localhost:9093
```

Something like this? I couldn't find docs for this.
