### ISSUE TITLE
Should temp variables (prefixed with __tmp) get deleted before ingestion?

### ISSUE THREAD

**Issue by akettmann-e24** [GoogleCloudPlatform/prometheus-engine#304]
I am not super well versed in Prometheus itself, but I am attempting to relabel and the prefix `__tmp` is called out as a temporary place to store data when you can't get what you need done in one step. However if I use that, the labels persist and get saved to GMP, unless I specifically drop that label. My expectation here is that anything prefixed with `__tmp` would get dropped once all my rules are done. 

Some docs/articles tend to suggest that it is expected for it to drop the values? Though not the latest official docs? 

This is taken from my `PodMonitoring.spec.endpoints[].metricRelabeling`

```yaml
        - action: replace
          sourceLabels:
            - name
          targetLabel: __tmp_lp_and_direction
          regex: ets\.default\.translate-\w+\.(.*)\.async\.(\w+)
          replacement: ${1}@${2}
          # Put the language_pair_id into place
        - action: replace
          sourceLabels:
            - __tmp_lp_and_direction
          regex: (.*)@(.*)
          targetLabel: language_pair_id
          replacement: ${1}
        # Put the direction (in or out) into place
        - action: replace
          sourceLabels:
            - __tmp_lp_and_direction
          regex: (.*)@(.*)
          targetLabel: direction
          replacement: ${2}
```

Just looking for clarification if I should or should not need to drop __tmp prefixed labels.
