### ISSUE TITLE
PromQL queries fail, but MQL works

### ISSUE THREAD

**Issue by willchan** [GoogleCloudPlatform/prometheus-engine#325]
As a workaround for #223, I set up [self-deployed collection](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged#config-unmg-collection) running in my single node kubeadm cluster so I could scape the kubelet cadvisor, with a config like:

```
global:
  scrape_interval: 60s
scrape_configs:
  - job_name: "kubernetes-cadvisor"
      - role: node

    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

    metric_relabel_configs:
      - source_labels: [container]
        regex: "^$|POD"
        action: drop
      - regex: "id"
        action: labeldrop
```

At first I thought the metrics weren't getting ingested, because I could not query `container_cpu_usage_seconds_total` with my [self-deployed prometheus frontend](https://cloud.google.com/stackdriver/docs/managed-prometheus/query#promui-deploy), nor [the Managed Service for Prometheus page](https://cloud.google.com/stackdriver/docs/managed-prometheus/query#gmp-promql-in-monitoring). I got `Empty query result`, although the UIs would both auto-complete the metrics when I typed into the UI. This implied to me that they somehow knew about the metric, but I couldn't query them.

When I tried the [Cloud Monitoring Metrics Explorer](https://cloud.google.com/stackdriver/docs/managed-prometheus/query#ui-monitoring), I was able to see the metrics. I'm not sure if it's something about this metric, or the # of labelsets (53), or what, but AFAICT MQL works to query it, but PromQL returns an empty query.
