### ISSUE TITLE
collector OOMKilled crashloop in GKE Autopilot

### ISSUE THREAD

**Issue by willchan** [GoogleCloudPlatform/prometheus-engine#338]
We've been running GMP managed collectors in our GKE Autopilot by deploying manifests, per https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#config-mgd-collection, for half a year now. We've seen crashlooping before, but I only recently dove into it and noticed that the crashes, at least of late, are OOMKilled.

```
  - containerID: containerd://f011670b9de0ec82bed8130d76e818505802b95313118adbc2066835f9c20231
    image: gke.gcr.io/prometheus-engine/prometheus:v2.35.0-gmp.2-gke.0
    imageID: gke.gcr.io/prometheus-engine/prometheus@sha256:02449f32a9fa8ab02c529eb34aa5c13f49d5b6c56f5d3cf23ff7ca23af6eb7d2
    lastState:
      terminated:
        containerID: containerd://f011670b9de0ec82bed8130d76e818505802b95313118adbc2066835f9c20231
        exitCode: 137
        finishedAt: "2022-09-30T16:09:41Z"
        reason: OOMKilled
        startedAt: "2022-09-30T16:08:50Z"
```

I looked at the different Pods in the DaemonSet, and their memory utilization varies. My understanding is the collectors only scrape Pods on the same Node, so what's probably the cause of the disparate memory utilization is the heterogeneity in the Pods on Nodes, or rather, the Pods' exposed metrics which the collector is scraping and exporting to Monarch.

DaemonSet memory usage:
![image](https://user-images.githubusercontent.com/466033/193313605-4e9bdf91-d025-40f9-a1ff-7290b0f6563c.png)

Healthy Pod memory usage:
![image](https://user-images.githubusercontent.com/466033/193313761-4faf364f-221f-477e-a8fc-669568791529.png)

OOMKilled Pod memory usage:
![image](https://user-images.githubusercontent.com/466033/193313807-1de6040e-d772-4bc4-bd9b-e13b77cc438c.png)

Given this info, I think GKE Autopilot's default VerticalPodAutoscaler is learning a memory limit that is too low for some Pods. I'm not really sure whose bug this should be. One could say that VPA is learning too low of a limit, but this value seems to work for most of the Pods in the DaemonSet. So maybe the problem is that the Pods in the DaemonSet shouldn't have heterogenous memory usage. That's what I'm leaning to. So I think this is probably a GMP collector bug.

The net result is that some of my Pods go long periods (many hours, perhaps days) without having their metrics scraped, due to the Node-local collector Pod crashlooping. I also suspect it's our Pod that exports the most timeseries that is not getting scraped, since I frequently see alerts firing that rely on those timeseries.

I think I can work around this by applying a custom VerticalPodAutoscaler with a higher memory limit, but it doesn't seem like that should be necessary.
