### ISSUE TITLE
way to disable Managed Alertmanager?

### ISSUE THREAD

**Issue by parkedwards** [GoogleCloudPlatform/prometheus-engine#355]
hello there - if we opt to self-deploy Alertmanager with GMP, is there a way to disable the automatically created alertmanager deployment / service?

https://cloud.google.com/stackdriver/docs/managed-prometheus/rules-managed#self-deployed_alertmanager

**Comment by damemi** [comment]
Hi @parkedwards, by default the managed Alertmanager doesn't do anything or interfere with self-deployed Alertmanagers. So simply by not configuring it, it is essentially "disabled". If you want to go a step further, you could try scaling the MAM statefulset to [0 replicas](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/cmd/operator/deploy/operator/12-alertmanager.yaml#L48), but this may only work if you are running [GMP unmanaged](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged).

For our reference, could you share why you need to disable the managed Alertmanager? Thanks

**Comment by parkedwards** [comment]
@damemi makes sense, we'll leave the MAM set un-configured

> For our reference, could you share why you need to disable the managed Alertmanager? Thanks

Sure thing, so we're opting to self deploy our Alertmanager instances.  Ideally, we wouldn't be running any other Alertmanager deployment or statefulset (eg. the Managed ones), just to conserve on resource usage and reduce confusion for anyone else on the team

**Comment by robmonct** [comment]
It would be nice to be able to disable managed AlertManager to avoid confusion.

**Comment by djfinnoy** [comment]
We just upgraded to v0.5.0, and spent half a hour figuring out a way to disable the managed alertmanager.

**Why?**
- We don't need it.
- It adds confusion; there is already an alertmanager instance running in the cluster
- It failed to deploy due to kustomization patches intended for the "real" alertmanager instance.

**How?**

We have to deploy GMP via the manifests, the addon installation isn't flexible enough for our needs (we need istio-sidecars, and we don't allow manual configuration through kubectl: everything should be code).
Since there isn't a Helm chart for GMP, we have to use kustomize. It's fairly straightforward to configure GMP to suit your needs via kustomizations:

```
# ./kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.5.0/manifests/setup.yaml
  - https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.5.0/manifests/operator.yaml


patchesStrategicMerge:
  - delete-google-managed-alertmanager.yaml

patches:
  - target:
      name: config
      kind: OperatorConfig
    patch: |-
      # Connect GMP with our self-managed alertmanager 
      - op: add
        path: /rules
        value:
          alerting:
            alertmanagers:
            - name: alertmanager
              namespace: monitoring
              port: 9093

  - target:
      name: gmp-system
      kind: Namespace
    patch: |-
      # Add Istio sidecars to the GMP so Kiali graphs make sense
      - op: add
        path: /metadata/labels
        value:
          istio-injection: enabled

---

# ./delete-google-managed-alertmanager.yaml

$patch: delete
apiVersion: v1
kind: Service
metadata:
  namespace: gmp-system
  name: alertmanager
---
$patch: delete
apiVersion: v1
kind: Secret
metadata:
  namespace: gmp-system
  name: alertmanager
---
$patch: delete
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: gmp-system
  name: alertmanager

```
