### ISSUE TITLE
Custom NodeSelector/affinity on managed pods

### ISSUE THREAD

**Issue by julienFlowdesk** [GoogleCloudPlatform/prometheus-engine#364]
Hello,

As of today, the managed components within gmp-system are installed randomly on the GKE's nodes.
We would like to have the possibility to specify nodeAffinity/selectors to put the pods on some target NodePools.
This is an issue for us as the managed pods are scheduled on critical nodePools where Ram and Cpu should be dedicated for critical systems.

We use node **custom** labels to arrange our scheduling.

I have not seen a way to do it properly, apart from manually editing the K8s objects which isn't very useful for us as we use FluxCD to deploy our operatorConfigs and PodMonitoring.

Thank you

**Comment by pintohutch** [comment]
Hi @julienFlowdesk,

The only way to customize the PodSpec of managed resources is to edit the resources themselves. Note when doing this, the operator will not reconcile and overwrite your change, so this is supported. You can also change the manifests to suit your affinity needs at install time.

I'm not super familiar with FluxCD, but it looks like this is supported using [in-line patches](https://fluxcd.io/flux/get-started/#customize-podinfo-deployment)?

**Comment by julienFlowdesk** [comment]
Hello @pintohutch 

Flux does not seems to permit to patch resources it doesn't manage with the "patch" keyword .
However, there is a workaround with flux by recreating a subpart of the object containing the patch in the flux repository and adding the `kustomize.toolkit.fluxcd.io/ssa: merge` annotation. 
Finally made it work, here is a full example :

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: gmp-operator
  namespace: gmp-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: gmp-operator
      app.kubernetes.io/part-of: gmp
  template:
    spec:
      containers: []
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - workload
```

Thank you,
Cheers
