### ISSUE TITLE
Issue with rule-evaluator with self deploy alertmanager 

### ISSUE THREAD

**Issue by savanipoojan78** [GoogleCloudPlatform/prometheus-engine#385]
When I was following this steps :- https://cloud.google.com/stackdriver/docs/managed-prometheus/rules-unmanaged#eval-rules-unmanaged

I made changes in the `rule-evaluator` configmap 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rule-evaluator
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rule-evaluator
data:
  config.yaml: |
    global:
      external_labels: 
        test: global-rule-evaluator
      evaluation_interval: 30s
    alerting: 
      alertmanagers:
        - dns_sd_configs:
          - names:
            - alertmanager.monitoring.svc.cluster.local
          port: 9093
          type: A
    rule_files:
    - "/etc/rules/*.yaml"
```

After this changes i deploy the rule-evaluator deployment so that if any alert will trigger it will go to my self deploy alertmanager 

After this deployment i was seeing this error in the logs of `rule-evaluator` pods 

```
level=info ts=2022-12-01T13:06:27.137865623Z caller=main.go:450 msg="Loading configuration file" filename=/etc/config/config.yaml
level=error ts=2022-12-01T13:06:27.138282653Z caller=main.go:375 msg="Error reloading config" err="couldn't load configuration (--config.file=\"/etc/config/config.yaml\"): parsing YAML file /etc/config/config.yaml: yaml: unmarshal errors:\n  line 7: field dns_sd_configs not found in type config.AlertmanagerConfig\n  line 10: field port not found in type config.AlertmanagerConfig\n  line 11: field type not found in type config.AlertmanagerConfig"
```

Here it says that its parsing error and `dns_sd_configs not found in type config.AlertmanagerConfig` but as per the prometheus documentation :- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config
The configuration is there as i missing something here

image that i am using for the rule-evaluator :- `gke.gcr.io/prometheus-engine/rule-evaluator:v0.5.0-gke.0`

if you want to see the deployment file as well let me know i can add that file here as well but its the same which is mention over here :- https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/manifests/rule-evaluator.yaml

**Comment by pintohutch** [comment]
Hi @savanipoojan78,

This is indeed a bug! Thanks for reporting. I believe we just need to change the [import line](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/423cc251516d74465fa18d7c31784e0f1cd72b20/cmd/rule-evaluator/main.go#L50-L51) in the rule-evaluator to register all service discovery config types. I'll be iterating in #391 if you wanna take a look!

Cheers

**Comment by pintohutch** [comment]
To unblock you in the meantime,

Your DNS config looks like it's pointing to a alertmanager K8s service.  I believe you can use a `kubernetes_sd_config` to connect to the alertmanager. Something like:
```
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_service_port_number]
      separator: ;
      regex: 9093
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
      namespaces:
        own_namespace: false
        names:
        - monitoring
 ```

Would that be possible to try?

**Comment by savanipoojan78** [comment]
I have made those changes and now i am getting this error in the pod 

`level=error ts=2022-12-08T05:28:15.937903027Z caller=main.go:144 msg="Error loading config (--config.file=/etc/config/config.yaml)" err="parsing YAML file /etc/config/config.yaml: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into config.AlertmanagerConfigs"`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rule-evaluator
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rule-evaluator
data:
  config.yaml: |
    global:
      external_labels: 
        test: global-rule-evaluator
      evaluation_interval: 30s
    alerting: 
      alertmanagers:
        follow_redirects: true
        enable_http2: true
        scheme: http
        path_prefix: /
        timeout: 10s
        api_version: v2
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          separator: ;
          regex: alertmanager
          replacement: $1
          action: keep
        - source_labels: [__meta_kubernetes_service_port_number]
          separator: ;
          regex: 9093
          replacement: $1
          action: keep
        kubernetes_sd_configs:
        - role: endpoints
          kubeconfig_file: ""
          follow_redirects: true
          enable_http2: true
          namespaces:
            own_namespace: false
            names:
            - monitoring
    rule_files:
    - "/etc/rules/*.yaml"
```
This is what my config looks like rule-evaluator log the above line and goes into CrashLoopBackOff mode

**Comment by pintohutch** [comment]
Ah you need a `-` in front of `follow_redirects` as `alerting.alertmanagers` is an array, not a map.

Note - for the K8s-based service discovery to work for your rule-evaluator deployment, its `serviceAccount` will need to be able to discover alertmanager endpoints and services within the cluster. Typically, a `ClusterRole` similar to [this](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/423cc251516d74465fa18d7c31784e0f1cd72b20/cmd/operator/deploy/operator/03-role.yaml#L15-L33) will permit everything you need.

**Comment by savanipoojan78** [comment]
Ohh My bad Thank you for pointing that mistake but i ended up using this

```
alerting: 
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "region-monitoring-kube-pro-alertmanager.monitoring.svc:9093"
```

Which is working fine.
But i wanted a small help on this 

So we are running multiple GKE cluster(in future it may increase) and on each cluster we have kube-prometheus running which is using this image `gke.gcr.io/prometheus-engine/prometheus:v2.35.0-gmp.2-gke.0` and push all the metrics to GMP.

Now we have an central cluster which is running the Grafana and gmp-frontend running (gmp-fronted connected to GMP and Grafana connected to gmp-fronted) and alert-manager all the other GKE cluster has the rules and if any rules violet then its send that alert to this central alertmanager , now if i want to make any changes in the rule or alert i have to make those changes in like many cluster it becomes tedious , why i wanted to explore this rule-evaluator is it directly evaluate the rule against the GMP so if i just run the rule-evaluator in central cluster it resolve headache to maintain rules for each cluster. but while going through the Document here its says that (https://cloud.google.com/stackdriver/docs/managed-prometheus/rules-unmanaged#multi-project_and_global_rule_evaluation) 
`
We recommend that you run one instance of the rule evaluator in each Google Cloud project and region rather than running one instance that evaluates against many projects and regions
`
Now all the cluster send the metrics to just a single google project but cluster are running on different region. i know it says that it support multi-project rule evaluation, 

so my question is there any side-effect to using just a single rule-evaluator that run the rules against single google project but multiple GCP region?

And Thank you for this amazing Product  🎉🎉🎉 .
