### ISSUE TITLE
Configuring actions for relabel_configs

### ISSUE THREAD

**Issue by tomasgareau** [GoogleCloudPlatform/prometheus-engine#404]
I'm using a `monitoring.googleapis.com/v1.PodMonitoring` resource to scrape pods.

I'd like to configure this resource to _only_ scrape pods in the `Running` phase. The `monitoring.coreos.com/v1.PodMonitor` CR would allow me to add `relabel_configs` with:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: my-monitor
spec:
  podMetricsEndpoints:
  - port: my-port
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_phase]  # <--- HERE
      action: keep
      regex: Running
  selector:
    matchLabels:
      component: my-component
```

but I don't see a way to configure a similar `keep` action `relabel_config` with the `monitoring.googleapis.com/v1.PodMonitoring` resource. This resource only provides **`metric_relabel_configs`** via the [`metricRelabeling`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/doc/api.md#scrapeendpoint) field, which doesn't appear to be able to access the `__meta_kubernetes_pod_phase` label:

```yaml
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: my-podmonitoring
spec:
  selector:
    matchLabels:
     - my: label
  endpoints:
    - port: metrics
      interval: 30s
      metricRelabeling:
        - sourceLabels: [__meta_kubernetes_pod_phase]  # <--- no dice: not sure if this meta-label is available during metric relabeling
          action: keep
          regex: Running
        - etc...
```

the [`targetLabels`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/doc/api.md#targetlabels) field appears to configure `relabel_configs` rules, but doesn't appear to provide a way to specify a `keep` action.
