### ISSUE TITLE
can we add arbitrary custom labels to scraped samples?

### ISSUE THREAD

**Issue by parkedwards** [GoogleCloudPlatform/prometheus-engine#485]
hello!

I've been looking into using relabeling configs to **add an arbitrary label/value** to scraped metrics.  I've been looking at the `metricRelabeling` (eg. prometheus relabeling configs) inside of a `PodMonitoring` spec

...except that it doesn't appear to be working in a way I've seen it behave in vanilla Prometheus - in fact, I don't see the new labels at all.  Is this supported behavior in GMP?

example:
```yaml
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: my-service
spec:
  selector:
    matchLabels:
      app: my-service
  endpoints:
    - port: 3001
      path: /metrics
      interval: 15s
      metricRelabeling:
        - sourceLabels: [__name__]
          targetLabel: new_label
          replacement: foobar
```

i've also tried this configuration without the `sourceLabels` list, with the same (non) result

Am I misunderstanding how we can use this part of the config?  Thanks again for all the great work on this project!
