### ISSUE TITLE
[bug/docs] The operator requires endpoint's scrape interval, but docs say it's optional

### ISSUE THREAD

**Issue by Zebradil** [GoogleCloudPlatform/prometheus-engine#491]
According to the docs, `ScrapeEndpoint.interval` is optional (`required == false`, [ref](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.7.0/doc/api.md#scrapeendpoint)). However, I can't apply the following resource:

```yaml
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: argocd-metrics
  namespace: argocd
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
```

The validation error:

> admission webhook "validate.podmonitorings.gmp-operator.gmp-system.monitoring.googleapis.com" denied the request: invalid definition for endpoint with index 0: invalid scrape interval: empty duration string

I guess, the docs should be corrected.
