### ISSUE TITLE
Improve Pod and Container Security Context for Prometheus Frontend

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/prometheus-engine#520]
`prometheus-frontend` already has a container security context, but it can be improved: https://github.com/GoogleCloudPlatform/prometheus-engine/blob/0aad9daccde2771f0a1c02247f250a33d58a3572/examples/frontend.yaml#L57C1-L65

I would propose:

* Adding a `seccompProfile` (RuntimeDefault)
* Setting `readOnlyRootFilesystem: true`
* Adding a Pod Security Context
* Switching to a non-root base image ([`distroless` publishes `nonroot` tags](https://github.com/GoogleContainerTools/distroless))

**Comment by jawnsy** [comment]
These are the settings we're using:

For the container security context:

```yaml
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
```

For the pod security context:

```yaml
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
```

Also, topology spread constraints can be a good idea to improve reliability in the event of node or zone failure:

```yaml
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: prometheus-frontend
      - maxSkew: 1
        topologyKey: topology.gke.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: prometheus-frontend
```
