### ISSUE TITLE
gmp-operator OOMKilled when turning on targetStatus

### ISSUE THREAD

**Issue by andreasmh** [GoogleCloudPlatform/prometheus-engine#774]
We tried to enable targetStatus on the OperatorConfig, according to these docs: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#target-status

```yaml
apiVersion: monitoring.googleapis.com/v1
kind: OperatorConfig
metadata:
  namespace: gmp-public
  name: config
features:
  targetStatus:
    enabled: true
```

When that was enabled, the gmp-operator started crashlooping because it was being OOMKilled.
We saw no logs or anything that could indicate what the problem was from the operator pod.

When we tried to disable the targetStatus feature:
```yaml
apiVersion: monitoring.googleapis.com/v1
kind: OperatorConfig
metadata:
  namespace: gmp-public
  name: config
features:
  targetStatus:
    enabled: false
```
We got the following error:
```
operatorconfigs.monitoring.googleapis.com "config" could not be patched: Internal error occurred: failed calling webhook "validate.operatorconfigs.gmp-operator.gmp-system.monitoring.googleapis.com" : failed to call webhook: Post "https://gmp-operator.gmp-system.svc:443/validate/monitoring.googleapis.com/v1/operatorconfigs?timeout=10s": dial tcp 10.13.51.53:10250: connect: connection refused
```
So basically, because the gmp-operator was being OOMKilled very soon after startup, we had real issues in trying to change the configuration because the validating webhook is hosted by the gmp-operator.

**Things we tried to go back to a working state:**

- Change OperatorConfig to disable targetStatus - Failed due to validating webhook
- Increase memory limits to 4gb on the deployment - Did not help, new pod got OOMKilled as well, and then the deployment was changed back to 2gb very quickly

**Thing that ultimately worked:**

- Kill the gmp-operator pod, wait for it to start, and quickly try to change the OperatorConfig to disable targetStatus before it gets OOMKilled a few seconds later.

**How I would have liked things to work:**

- gmp-operator not being OOMKilled
- No circular dependency between the config of the gmp-operator and the gmp-operator (with validating webhook hosted by the gmp-operator that is configured by the OperatorConfig)
- Being able to somehow change the resource requests and limits for the gmp-operator deployment

I have no idea why the gmp-operator is being OOMKilled, there is no shortage of memory on the worker nodes, and there are no logs being output from the gmp-operator that would indicate a problem.

We did this in two separate projects and GKE clusters, with the same result.
Some stats that might be interesting and or help some debugging on why targetStatus enablement makes gmp-operator get OOMKilled:

One cluster has 1800~ pods,  270~ Podmonitoring resources, 1 ClusterPodMonitoring resource
The other cluster has 1000~ pods, 310~ Podmonitoring resources, 1 ClusterPodMonitoring resource

 The operator is running this version: operator:v0.8.0-gke.4
 GKE version 1.27.7-gke.1121000
