### ISSUE TITLE
Documentation or examples could demonstrate TargetLabels FromPod

### ISSUE THREAD

**Issue by strideynet** [GoogleCloudPlatform/prometheus-engine#875]
None of the examples or documentation beyond the API reference demonstrate how to scrape the pod labels as metric labels. This makes it harder than necessary to get going.

For my future reference, and the reference of anyone else:

```yaml
spec:
  endpoints:
  - interval: 1m
    port: my-port
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
  targetLabels:
    fromPod:
    - from: foo
    - from: foo/bar
      to: foo_bar
    metadata:
    - pod
    - container
```

Specify `from` as the name of the pod label you wish to have added to the metric labels. You may also need to specify `to` to provide the name the label should be on the metric - this is necessary if the pod label is not compatible with the metric labels (e.g contains characters such as /)
