### ISSUE TITLE
Support for ProbeMonitoring

### ISSUE THREAD

**Issue by dsaintilma-flinks** [GoogleCloudPlatform/prometheus-engine#91]
Hello,

I was wondering if adding an API endpoint for scraping Probe for exporters like blackbox or ssl is planned?

That's all.
Thanks!

**Comment by fabxc** [comment]
We have definitely thought about that use case and want to enable it. Though we don't have a concrete design yet on how to integrate that with the current CRDs.

Our recommendation in the meantime is to run the GMP Prometheus binary as a sidecar to the blackbox_exporter with a static config that only scrapes the blackbox exporter.

**Comment by masterlittle** [comment]
Any update on this if it's going to be picked up?

**Comment by lyanco** [comment]
Heya, we are not currently working on this. In the meantime you can use self-deployed collection to do this: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged

**Comment by bwplotka** [comment]
Another user asked for this today, so it might good idea to prioritise it. I am not yet sure we need Probe CR with this, as technically this could be an opinionated field in PodMonitor as well for simplicity. 

Note that probing is technically possible with PodMonitors with something like:

```
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
(...)
spec:
  selector:
    matchLabels:
       (...)
  endpoints:
  - port: http
    scheme: http
    interval: 60s
    path: "/probe"
    params:
      module:
      - http_2xx
      target:
      - "http://target1/"
```

Two main limitations are: 
1. You have to create separate PodMonitor per target/param (port has to be unique) and no dynamic parameter mangling as described [here](https://prometheus.io/docs/guides/multi-target-exporter/#querying-multi-target-exporters-with-prometheus) is possible.
2. You have "wrong" instance label (as explained [here](https://prometheus.io/docs/guides/multi-target-exporter/#querying-multi-target-exporters-with-prometheus)) as you cannot relabel instance label (you will get  cannot relabel with action "replace" onto protected label "instance"` error).

**Comment by pintohutch** [comment]
Interesting. So IIUC the main reason we can't support the probe monitoring use case in a single `PodMonitoring` is that the `job_name`s are not unique if the `port`s are not unique within the spec.

However, if we switched to using the index of the endpoint, as prometheus-operator [does](https://github.com/prometheus-operator/prometheus-operator/blob/fa7f9eb24e8cdcde574a2988c2286677b1716b9e/pkg/prometheus/promcfg.go#L1949), rather than the [port](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/f0601efa648d66d4aefdde7d2532f0ce3829b5d2/pkg/operator/apis/monitoring/v1/types.go#L701), then this would be possible.

Aside: I'm curious then, if probe-style monitoring works with prometheus-operator's `ServiceMonitor`, then what does the [`Probe`](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.Probe) custom resource provide? A "nicer" API for probing? AFAICT it's most conventionally used for static target scraping.

**Comment by QuerQue** [comment]
> Our recommendation in the meantime is to run the GMP Prometheus binary as a sidecar to the blackbox_exporter with a static config that only scrapes the blackbox exporter.

Hi @fabxc I have GMP Prometheus running in non-GKE env and I use GCP cloud monitoring to visualize node_exporter metrics. I also want to use blackbox exporter. I'm not sure if I understand this workaround correctly. Please take a look and let me know if that's what you recommend.
1. Managed collection that scraps node_exporter leaves as it is.
2. New deployment blackbox-exporeter with sidecar container  and config like below:
```
  spec:
    ...
    secrets:
    - gmp-test-sa
    containers:
    - name: prometheus
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /gmp/key.json
      volumeMounts:
      - name: secret-gmp-test-sa
        mountPath: /gmp
        readOnly: true
```

plus prometheus config as configMap with
```
global:
  external_labels:
    project_id: PROJECT_ID
    location: REGION
    cluster: CLUSTER_NAME
```

And scraping settings of course
